### ISSUE TITLE
Please consult the author

### ISSUE THREAD

**Issue by zhm1006** [lunan0320/Federated-Learning-Knowledge-Distillation#1]
I would like to ask, if I change the number of clients to 50, what other modifications are needed to ensure that the code runs

**Comment by lunan0320** [comment]
In option.py, change the parameter num_clients to 50, and increase the number of epochs for better performance.
Also, you can change the model or algorithm if you need. You can directly run python main.py, it is not affected by the number of clients.
Hope it can help you.
